# Generated by Django 5.0.7 on 2024-07-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cetaf_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='version',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institutions',
            name='version',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
