# Generated by Django 5.0.7 on 2024-08-07 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cetaf_api', '0002_collections_version_institutions_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institutions',
            old_name='creation_date',
            new_name='harvesting_date',
        ),
    ]
