# Generated by Django 5.0.7 on 2024-08-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cetaf_api', '0003_rename_creation_date_institutions_harvesting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutions',
            name='modification_date',
            field=models.DateTimeField(),
        ),
    ]
