# Generated by Django 5.0.7 on 2024-10-18 12:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cetaf_api', '0004_alter_institutions_modification_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionsNormalized',
            fields=[
                ('fpk', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('data', models.JSONField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['uuid'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionsNormalized',
            fields=[
                ('fpk', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('data', models.JSONField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['uuid'],
            },
        ),
        migrations.RemoveField(
            model_name='collections',
            name='fk_institution',
        ),
        migrations.AddField(
            model_name='collections',
            name='fk_collection_normalized',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cetaf_api.collectionsnormalized'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collections',
            name='fk_institution_normalized',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cetaf_api.institutionsnormalized'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institutions',
            name='fk_institution_normalized',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cetaf_api.institutionsnormalized'),
            preserve_default=False,
        ),
    ]
