# Generated by Django 5.0.7 on 2024-10-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cetaf_api', '0006_collections_uuid_collection_normalized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionsnormalized',
            name='modification_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='institutionsnormalized',
            name='modification_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
