# Generated by Django 5.0.7 on 2024-10-18 15:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cetaf_api', '0007_alter_collectionsnormalized_modification_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionsnormalized',
            name='fk_institution_normalized',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cetaf_api.institutionsnormalized'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectionsnormalized',
            name='uuid_institution_normalized',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
