# Generated by Django 5.0.7 on 2024-10-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cetaf_api', '0008_collectionsnormalized_fk_institution_normalized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='source_uri',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
