"""
Django settings for cetaf_survey_api project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1l-hpeq2lpzr*ekxpfwoz=f%i1#!8k-t_a=n-@=ka5v-xt2bj8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["123.456.123.456", "127.0.0.1", "localhost"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'cetaf_api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cetaf_survey_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cetaf_survey_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': '',
        'USER': 'postgres',
        'PASSWORD': '',
        'HOST': '',
        'PORT': '5432',
    }
}

ES_URL="http://localhost:9200/"
ES_INDEX_INSTITUTIONS="cetaf_dissco_institutions_dev"
ES_INDEX_COLLECTIONS="cetaf_dissco_collections_dev"

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny'
    ]
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s %(levelname)s [%(name)s:%(lineno)s] %(module)s %(process)d %(thread)d %(message)s'
        }
    },
    'handlers': {
        'gunicorn': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'formatter': 'verbose',
            'filename': '/opt/cetaf_passport_api/logs/gunicorn.errors',
            'maxBytes': 1024 * 1024 * 100,  # 100 mb
        }
    },
    'loggers': {
        'gunicorn.errors': {
            'level': 'DEBUG',
            'handlers': ['gunicorn'],
            'propagate': True,
        },
    }
}
####
CETAF_DATA_ADDRESS={
        "institutions": "1gpZt4gX9qOXWY2fJNcI6XlnBgQDBsFOxyoFqofbymn8",
        "collection_overview": "1iIZqWxmkqdx5VGQkXgngOoERO--lCWo64KbF75fJ5hM",
    }
    
DEFAULT_QUERY_SIZE=10    
    
GOOGLE_AUTH_FILE="json_file"
GOOGLE_CLOUD_REFRESH_TOKEN=""
GOOGLE_CLOUD_CLIENT_ID='xxxxxx.apps.googleusercontent.com'
GOOGLE_CLOUD_SECRET="xxxxx"
GOOGLE_CLOUD_REDIRECT_URI="https://developers.google.com/oauthplayground"
GOOGLE_CLOUD_REFRESH_URL="https://www.googleapis.com/oauth2/v4/token"

MAPPING_G_SHEET={
    "institutions": {
        "timestamp":0,
        "timestamp_format":"%d/%m/%Y %H:%M:%S",
        "timestamp_default":"01/01/0001 00:00:00",
        "fields":
        {
            8: "name_institution_en",
            9: "name_institution_en_alternate",
            12: "original_name",
            "address":
            {
                21 : "street",
                22: "city",
                23 :"province",
                24: "postcode" ,
                25: "country"
            }
            ,
            "contact":
            {
                27: "phone",
                28: "mail"
            },
            "social_network":
            {
                30: "X",
                31: "Facebook",
                32: "Instagram",
                33: "LinkedIn",
                34: "YouTube",
            },
            "institution_data":
            {
                10: "logo",
                29: "website",
            },
            "direction":
             {
                41: "title",
                43 : "first_name",
                44: "last_name",
                45: "phone",
                46: "mail",
                47: "orcid"
             },
             "organisation":
             {
                48: "chart_description",
                49: "chart_url",
                50: "chart_file",
                51: "governing_and_exectutive_bodies",
                52: "year_data"
             },
             58: "cetaf_membership",
             "cetaf_representative":
             {
                59: "title",
                61 : "first_name",
                62: "last_name",
                64: "phone",
                63: "mail",
                65: "orcid",
                66: "role_in_institution"
             },
             "cetaf_executive_1":
             {
                69: "title",
                71: "first_name",
                72: "last_name",
                73: "phone",
                74: "mail",
                75: "orcid",
                76: "role_in_institution"
             },
             "cetaf_executive_2":
             {
                79: "title",
                81: "first_name",
                82: "last_name",
                83: "phone",
                84: "mail",
                85: "orcid",
                86: "role_in_institution"
             }
            
            
        },
        "identifiers_api":
        {
            35: "ror"
        },
        "main_identifier_db": {
            "fields" :
            {
                8 :"name_institution_en",
                9: "name_institution_en_alternate",
                12: "original_name",
             },
             "null_value":"Other"
        },
        "other_identifiers":
        {
            35: "ror",
            36: "grid",
            37: "index_herbarium",
            38: "wikidata",
            39: "isni",
            40: "grscicoll",
        }
        ,
        "apis":
        {
            #keep this order for grscicoll
            "ror":35,
            "grscicoll_institutions":40,
            "grscicoll_collections_from_institutions" : None
        }
        
    }
    
}

#alternate mapmping identifier in column
MAPPING_G_SHEET_OVERVIEW={

    "cetaf_collection_overview":
    {
        "institution_id_fields":
        {
            "institution_name":4,
            "alternate_institution_name":5
        },
        "appended_excel":
        {
            "collection_size": { "col":25, "sheet": "Collection overview"}
        }
    }
}

#keep this order for grscicoll
APIS_SHEET={
    "ror": {
            "endpoint":"https://api.ror.org/v2/organizations/",

            "mapping":
                {
                }
    },
    "grscicoll_institutions": {
            "endpoint":"https://api.gbif.org/v1/grscicoll/institution/latimerCore?code=",

            "mapping":
                {
                }
    },
    "grscicoll_collections_from_institutions": {
            "endpoint":"https://api.gbif.org/v1/grscicoll/collection/latimerCore?institutionKey=",

            "mapping":
                {
                }
    
    }
    
}

