"""
Django settings for cetaf_survey_api project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ''

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["193.190.223.60", "127.0.0.1", "localhost"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'cetaf_api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cetaf_survey_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cetaf_survey_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': '',
        'USER': '',
        'PASSWORD': '',
        'HOST': '',
        'PORT': '',
    }
}

ES_URL="https://darwin.naturalsciences.be/" #"http://localhost:9200/"
ES_INDEX_INSTITUTIONS="cetaf_passport_institutions" #"cetaf_dissco_institutions_dev"
ES_INDEX_COLLECTIONS="cetaf_passport_institutions" #"cetaf_dissco_collections_dev"

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny'
    ]
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s %(levelname)s [%(name)s:%(lineno)s] %(module)s %(process)d %(thread)d %(message)s'
        }
    },
    'handlers': {
        'gunicorn': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'formatter': 'verbose',
            'filename': '/opt/cetaf_passport_api/logs/gunicorn.errors',
            'maxBytes': 1024 * 1024 * 100,  # 100 mb
        }
    },
    'loggers': {
        'gunicorn.errors': {
            'level': 'DEBUG',
            'handlers': ['gunicorn'],
            'propagate': True,
        },
    }
}
####
CETAF_DATA_ADDRESS={
        "institutions": "",
        "collection_overview": "",       
        "collection_root_folder":""  
      
    }
    
DEFAULT_QUERY_SIZE=10    
    
GOOGLE_AUTH_FILE="/"
GOOGLE_CLOUD_REFRESH_TOKEN=""
GOOGLE_CLOUD_CLIENT_ID=''
GOOGLE_CLOUD_SECRET=""
GOOGLE_CLOUD_REDIRECT_URI="https://developers.google.com/oauthplayground"
GOOGLE_CLOUD_REFRESH_URL="https://www.googleapis.com/oauth2/v4/token"

GOOGLE_SHEET_URL="https://docs.google.com/spreadsheets/d/"

MAPPING_G_SHEET={
    "institutions": {
        "timestamp":0,
        "timestamp_format":"%d/%m/%Y %H:%M:%S",
        "timestamp_default":"01/01/0001 00:00:00",
        "fields":
        {
            8: "name_institution_en",
            9: "name_institution_en_alternate",
            12: "original_name",
            "address":
            {
                21 : "street",
                22: "city",
                23 :"province",
                24: "postcode" ,
                25: "country"
            }
            ,
            "contact":
            {
                27: "phone",
                28: "mail"
            },
            "social_network":
            {
                30: "X",
                31: "Facebook",
                32: "Instagram",
                33: "LinkedIn",
                34: "YouTube",
            },
            "institution_data":
            {
                10: "logo",
                29: "website",
            },
            "direction":
             {
                41: "title",
                43 : "first_name",
                44: "last_name",
                45: "phone",
                46: "mail",
                47: "orcid"
             },
             "organisation":
             {
                48: "chart_description",
                49: "chart_url",
                50: "chart_file",
                51: "governing_and_executive_bodies",
                52: "year_data"
             },
             58: "cetaf_membership",
             "cetaf_representative":
             {
                59: "title",
                61 : "first_name",
                62: "last_name",
                64: "phone",
                63: "mail",
                65: "orcid",
                66: "role_in_institution"
             },
             "cetaf_executive_1":
             {
                69: "title",
                71: "first_name",
                72: "last_name",
                73: "phone",
                74: "mail",
                75: "orcid",
                76: "role_in_institution"
             },
             "cetaf_executive_2":
             {
                79: "title",
                81: "first_name",
                82: "last_name",
                83: "phone",
                84: "mail",
                85: "orcid",
                86: "role_in_institution"
             }
            
            
        },
        "array_fields":
        {
            3: {"name": "membership", "delimiter":"," }
        },        
        "identifiers_api":
        {
            35: "ror"
        },
        "main_identifier_db": {
            "fields" :
            {
                8 :"name_institution_en",
                9: "name_institution_en_alternate",
                12: "original_name",
             },
             "null_value":"Other"
        },
        "other_identifiers":
        {
            35: "ror",
            36: "grid",
            37: "index_herbarium",
            38: "wikidata",
            39: "isni",
            40: "grscicoll",
        }
        ,
        "apis":
        {
            #keep this order for grscicoll
            "ror":35,
            "grscicoll_institutions":40,
            "grscicoll_collections_from_institutions" : None
        }
        
    }
    
}

#alternate mapmping identifier in column
MAPPING_G_SHEET_OVERVIEW={

    "cetaf_collection_overview":
    {
        "institution_id_fields":
        {
            "institution_name":4,
            "alternate_institution_name":5
        },
        "appended_excel":
        {
            "collection_size": { "col":25, "sheet": "Collection overview"}
        }
    }
}

#keep this order for grscicoll
APIS_SHEET={
    "ror": {
            "endpoint":"https://api.ror.org/v2/organizations/",

            "mapping":
                {
                }
    },
    "grscicoll_institutions": {
            "endpoint":"https://api.gbif.org/v1/grscicoll/institution/latimerCore?code=",

            "mapping":
                {
                }
    },
    "grscicoll_collections_from_institutions": {
            "endpoint":"https://api.gbif.org/v1/grscicoll/collection/latimerCore?institutionKey=",

            "mapping":
                {
                }
    
    }    
}

COLLECTION_ACRONYMS_MAPPING={
    'AFP Algae, Fungi, Plants (old botany)':'AFP',
    'Botany / Algae':'AFP-ALG',
    'Botany / Bryophites':'AFP-BRY',
    'Botany / Fungi and lichen':'AFP-FUN',
    'Botany / others':'AFP-OTH',
    'Botany / PGR':'AFP-PGR',
    'Botany / Pteridophites':'AFP-PTE',
    'Seeds':'AFP-SEE',
    'Anthropology':'ANT',
    'Anthtopology - AGR':'ANT-AGR',
    'Archeology':'ANT-ARC',
    'Human biology / human evolution':'ANT-BIO',
    'Anthropology (non specified)':'ANT-NS',
    'Anthropology (others)':'ANT-OTH',
    'AST':'AST',
    'AST-IMP':'AST-IMP',
    'AST-MET':'AST-MET',
    'AST-OTH':'AST-OTH',
    'AST-RET':'AST-RET',
    'Data':'DAT',
    'Data / digital born':'DAT-DIB',
    'Data / digitization':'DAT-DIG',
    'Data / measurements':'DAT-MEA',
    'Data / metadata':'DAT-MET',
    'Data / observation':'DAT-OBS',
    'Data / others':'DAT-OTH',
    'ECO':'ECO',
    'ECO-DNA':'ECO-DNA',
    'ECO-OTH':'ECO-OTH',
    'Geology':'GEO',
    'GEO-ICE':'GEO-ICE',
    'GEO-LGS':'GEO-LGS',
    'Geology / Minerals':'GEO-MIN',
    'GEO-MSS':'GEO-MSS',
    'Geology - others':'GEO-OTH',
    'Geology - petrology':'GEO-PET',
    'Geology  sediments':'GEO-SED',
    'Geology - soils':'GEO-SOI',
    'Heritage sciences':'HER',
    'Heritage sciences / documents':'HER-DOC',
    'Heritage sciences / library':'HER-LIB',
    'Heritage sciences / models':'HER-MOD',
    'Heritage sciences / others':'HER-OTH',
    'Heritage sciences / pictures':'HER-PIC',
    'Heritage sciences / sounds':'HER-SOU',
    'Invertebrates':'INV',
    'Invertebrates / Arthropods - Archnids':'INV-ARA',
    'Invertebrates / Cnidaria':'INV-CNI',
    'Invertebrates / Crustaceans ':'INV-CRU',
    'Invertebrates / Echinodermata':'INV-ECH',
    'Invertebrates / Entomology':'INV-ENT',
    'Invertebrates  / IGR':'INV-IGR',
    'Invertebrates / Mollusca':'INV-MOL',
    'Invertebrates / Others':'INV-OTH',
    'Invertebrates / POR':'INV-POR',
    'Micro-organisms':'MIC',
    'Micro-organisms / ALG':'MIC-ALG',
    'Micro-organisms / Bacteria':'MIC-BAC',
    'Micro-organisms / EUK':'MIC-EUK',
    'Micro-organisms / Others':'MIC-OTH',
    'Micro-organisms / Phages':'MIC-PHA',
    'Micro-organisms / Plasmids':'MIC-PLA',
    'Micro-organisms / Protozoa':'MIC-PRO',
    'Micro-organisms / Viruses':'MIC-VIR',
    'Micro-organisms / Yeast and fungi':'MIC-YEA',
    'Paleontology':'PAL',
    'Paleontology / Botany':'PAL-AFP',
    'Paleontology / Invertebrates':'PAL-INV',
    'Paleontology / Non specified':'PAL-NS',
    'Paleontology / Others':'PAL-OTH',
    'Paleontology / Vertebrates':'PAL-VER',
    'Zoology vertebrates':'VER',
    'Zoology vertebrates / Amphibians':'VER-AMP',
    'Zoology vertebrates / Birds':'VER-BIR',
    'Zoology vertebrates / Fishes':'VER-FIS',
    'Zoology vertebrates / Mammalogy':'VER-MAM',
    'Zoology vertebrates / Non specified':'VER-NS',
    'Zoology vertebrates / Others':'VER-OTH',
    'Zoology vertebrates / Reptilians':'VER-REP',
    'Zoology vertebrates / VGR' : 'VER-VGR',
      'AFP': 'AFP',
     'ALGAE':'AFP-ALG',
     'ARACHNIDS':'INV-ARA',
     'ASTROGEOLOGY-OTHERS': 'AST-OTH',
     'BRYOPHYTES':'AFP-BRY',
     'CNIDARIA-JELLYFISH-CORAL-ANEMONES': 'INV-CNI',
     'CRUSTACEANS-AND-MYRIAPODS':'INV-CRU',
     'ECHINODERMATA-STARFISH-SEA-URCHINS-SEA-CUCUMBERS':'INV-ECH',
     'ECOLOGY-E-DNA':'ECO-DNA',
     'ECOLOGY-OTHER-ITEMS':'ECO-OTH',
     'ECOLOGY-UNSPECIFIED':'ECO-UNS',
     'GEOLOGY-OTHER':'GEO-OTH',
     'HERITAGE-DOCUMENTATION':'HER-DOC',
     'HERITAGE-SOUNDS':'HER-SOU',
     'INSECTS':'INV-ENT',
     'INV-UNSPECIFIED':'INV-UNS',
     'LIQUID-OR-GASEOUS': 'GEO-LGS',
     'MACROFUNGI-LICHENS-AND-MYXOMYCETES':'AFP-FUN',
     'MINERALS-AND-GEMS':'GEO-MIN',
     'MIXED-GEOLOGY':'GEO-MIX',
     'OTHER-BOTANY-OBJECTS':'AFP-OTH',
     'OTHER-INVERTEBRATES-ZOOLOGY-OBJECTS':'INV-OTH',
     'PALAEONTOLOGY-FOSSIL-INVERTEBRATES':'PAL-INV',
     'PALAEONTOLOGY-FOSSIL-VERTEBRATES':'PAL-VER',
     'PALAEONTOLOGY-OTHERS':'PAL-OTH',
     'PALAEONTOLOGY-PLANTS-AND-FUNGI':'PAL-AFP',
     'PALAEONTOLOGY-UNSPECIFIED':'PAL-UNS',
     'PETROLOGY':'GEO-PET',
     'PLANTS-GENETIC-RESOURCES':'AFP-DNA',
     'PORIFERA-SPONGES':'INV-POR',
     'PTERIDOPHYTES': '? PTERIDOPHYTES',
     'SEDIMENTS':'GEO-SED',
     'SEED-PLANTS':'AFP-SEE',
     'SOILS':'GEO-SOI',
     'TERRESTRIAL-FINDS-FALLS-E.G.-METEORITES': '? TERRESTRIAL-FINDS-FALLS-E.G.-METEORITES',
     'TERRESTRIAL-IMPACTA' : '? TERRESTRIAL-IMPACTA',
     'VERTEBRATES-AMPHIBIANS' :'VER-AMP',
     'VERTEBRATES-BIRDS':'VER-BIR',
     'VERTEBRATES-FISHES':'VER-FIS',
     'VERTEBRATES-GENETIC-RESSOURCES':'VEAR-DNA',
     'VERTEBRATES-MAMMALS':'VER-MAM',
     'VERTEBRATES-OTHERS':'VER-OTH',
     'VERTEBRATES-REPTILES':'VER-REP',
     'VERTEBRATES-UNSPECIFIED':'VER-UNS',
     'WATER-ICE':'GEO-ICE',
    
}

JSON_OUTPUT_FILTER_PROFILE={
    "demo_filter": [
                "/pager",
              "/data/@/data/data_list/@/data/main_metadata/description",
               "/data/@/data/parent_institution_list_identifiers/@type=grscicoll",
               "/data/@/data/parent_institution_list_identifiers/@type=grid"    
    ]
}

INTERNAL_COLLECTION_LINK="https://naturalheritage.africamuseum.be/cetaf_survey_api/collections/?operation=get_by_id&protocol=cetaf&values="

